spring:
  application:
    name: tender-hack-app
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-73-155-171.compute-1.amazonaws.com:5432/d9kao418qo0g18
    username: unxvhgodexwjso
    password: c2d724793499afa0a047805d2064e0e4a754720c726ae07e24a315a4cf14692d
  jpa:
    database: POSTGRESQL
    hibernate:
      dl-auto: none
  flyway:
    locations: classpath:db/migration, classpath:db/test-data

server:
  port: 10552
  shutdown: graceful
  servlet:
    context-path: /api/v1

jwt:
  secret: "t$%^en@der112HAcK@##"

out-system:
  #url: "https://emulate-tender-hack.herokuapp.com/api/v1"
  url: "http://localhost:10550/api/v1"
  key: "2db75760-bd8f-11ec-9d64-0242ac120002"
  endpoints:
    get-sessions: "/sessions/{sessionType}"
    get-session: "/session/{sessionId}"
    make-bet: "/session/{sessionId}/bet"

mailSender:
  subject: "Tag All - уведомление о котировочной сессии"
  userName:
  password: