spring:
  application:
    name: tender-hack-app
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bl
    username: postgres
    password: 2rnKmkJG!!
  jpa:
    database: POSTGRESQL
    hibernate:
      dl-auto: none
  flyway:
    locations: classpath:db/migration, classpath:db/test-data

server:
  port: 10552
  shutdown: graceful
  servlet:
    context-path: /api/v1

jwt:
  secret: 't$%^en@der112HAcK@##'
